Use `uniseg` to calculate `DisplayWidth`
cli/go-gh pull request #159
Opened 2024-04-29 15:38 UTC by maaslalani

Fixes https://github.com/cli/cli/issues/9018

Uses `uniseg.StringWidth` to calculate `DisplayWidth` which correctly aligns emojis.

2024-04-29 15:39 UTC, maaslalani commented
<img width="1718" alt="image" src="https://github.com/cli/go-gh/assets/42545625/a803ea65-d465-4ba5-bda4-22fb95cfcc4a">

2024-04-29 15:43 UTC, williammartin requested changes

2024-04-29 15:43 UTC, williammartin commented on pkg/text/text.go
> +	return uniseg.StringWidth(s)
**Change Requested**

Can you add the emoji from https://github.com/cli/cli/issues/9018 into the `TestDisplayWidth` test cases?

2024-04-29 15:53 UTC, maaslalani commented
@williammartin Had to switch to `lipgloss.Width` to account for ANSI sequences since `uniseg` doesn't strip ANSI before calculating width (one of the test cases included ANSI sequences), but `lipgloss` does then uses `uniseg.StringWidth` under the hood.

Added the multi-byte emoji test case as well!

2024-04-29 15:55 UTC, maaslalani commented on go.mod
> +	golang.org/x/sys v0.19.0
Let me know if you don't want to bump this.

2024-04-29 16:02 UTC, williammartin commented
Thanks. If we're expecting `DisplayWidth` to handle ANSI escape sequences then let's add a test for that as well.

I suppose for someone out there this could be a breaking change but I think it's edge case enough that I'd rather just accept it and then people could fix any hacky workarounds they might have had.

2024-04-29 16:05 UTC, maaslalani commented
Yep, there is already a test case for that! The tests were failing when I simply had `uniseg.StringWidth` because of the ANSI test case. Which is why I needed to swap out for lipgloss to pass all tests cases.

2024-04-29 16:06 UTC, maaslalani commented
Test case for ignoring ANSI sequences when calculating width is here: https://github.com/cli/go-gh/blob/trunk/pkg/text/text_test.go#L282-L287 (fails when _just_ using `uniseg.StringWidth`, passes when using `lipgloss.Width`)

2024-04-29 16:11 UTC, williammartin commented
Well, that's testing the public API of `PadRight` but it's just an implementation detail that `PadRight` uses `DisplayWidth`. Refactoring `PadRight` would then lose all our confidence that `DisplayWidth` handles ANSI codes. I want to both ensure that `DisplayWidth` enforces this behaviour, and I want it to be communicated to future maintainers in the tests because I had no idea that it was expected when you first opened the PR.

2024-04-29 16:13 UTC, maaslalani commented
Ah you're totally right, there is also a test case directly for color codes in `DisplayWidth` as well:

* https://github.com/cli/go-gh/blob/5840c447a66255f2822dfc9be315be0f9ff1d6d2/pkg/text/text_test.go#L360-L363

2024-04-29 16:17 UTC, williammartin commented
Haha sorry I should have also looked closer. I think I got red herring-ed by your link because I assumed if it existed already you would definitely have linked it 😅 

I can confirm that test fails just using `uniseg.StringWidth`:

```
--- FAIL: TestDisplayWidth (0.00s)
    --- FAIL: TestDisplayWidth/color_codes (0.00s)
        /Users/williammartin/workspace/go-gh/pkg/text/text_test.go:388: 
            	Error Trace:	text_test.go:388
            	Error:      	Not equal: 
            	            	expected: 3
            	            	actual  : 12
            	Test:       	TestDisplayWidth/color_codes
```

No need for extra tests, this looks great to me, once I pull it into `cli/cli` and play with it, cheers.

2024-04-29 16:18 UTC, maaslalani commented
> I think I got red herring-ed by your link because I assumed if it existed already you would definitely have linked it 😅

Haha all good! I kind of missed that test case as well and definitely should have linked to that!

2024-04-29 16:28 UTC, williammartin commented
### Before

<img width="1719" alt="image" src="https://github.com/cli/go-gh/assets/1611510/1185e161-60d5-4beb-8a18-f8e25725e1fb">

(wow such codepoints: https://ardislu.dev/biggest-unicode-grapheme-cluster)

### After

<img width="1720" alt="image" src="https://github.com/cli/go-gh/assets/1611510/f2f781c5-81ac-4960-9f03-b07ee2267e53">

2024-04-29 16:30 UTC, williammartin approved these changes
I pulled this into `cli/cli` and it passed all the tests.

LGTM thanks a lot.

2024-04-29 16:32 UTC, merged

2024-05-04 02:14 UTC, Abeabenut reviewed
https://github.com/cli/cli/releases/tag/v2.48.0